Database:
  Type: SQLITE
  IdentifierType: UUID
  Hostname: localhost
  Port: 3306
  Database: database
  Username: admin
  Password: password
Settings:
  #if true, players can trade to other currencies even if they have never acquired them before
  Free-Trader-Currency-Market: false
Listeners:
  ComplexListeners: [ ]
  TinyListeners: [ ]