name: BlobEconomy
version: ${project.version}
main: io.github.anjoismysign.blobeconomy.BlobEconomy
api-version: 1.17
load: STARTUP
depend: [ BlobLib ]
softdepend:
  - PlaceholderAPI

commands:
  eco:
    description: "Manages economy"
    usage: "/eco <give/take> <player> <amount> <key('silver' is default)>"
    aliases: [ beco, blobeco, blobeconomy ]
  currency:
    description: "Manages currency"
    usage: "/currency <add/remove>"